/* `/ae/docs` 페이지 사전 — EN/KO. 🔴 이 파일은 **이 페이지 레인만** 고친다.
   v3.3 에 같은 문장이 이미 있으면 새 키를 만들지 말고 그 키를 그대로 써라(EN 번역이 붙어 있다).

   🔴 **툴 39종의 설명은 여기 없다.** 제품이 이미 양 로케일을 갖고 있고 `lib/docsData.ts` 가
   그걸 읽어 온다 — 여기에 손번역을 들이면 패널과 사이트가 다른 말을 하기 시작한다.
   패널·툴·이펙트 **이름**도 여기 적지 않는다(로케일 무관 영문). 예외는 `docs.fx.<slug>` —
   사이트 표기가 제품 표기와 갈라진 자리라 양 로케일에 **같은 문자열**을 적어 둔다.

   🔴 숫자는 자리표시자로: `{scripts}` 같은 건 `lib/copy.ts` 가 `lib/product.ts` 에서 채우고,
   `{n}` 은 렌더 쪽에서 실제 배열 길이로 채운다(패널 수·카테고리별 툴 수·릴리스 항목 수).
   사전에 숫자를 박으면 그 순간 낡는다. */
import type { Dict } from './types';

const DOCS: Dict = {
  en: {
    /* ── 네비 · 목차 (섹션 data-name 과 같은 키를 쓴다) ── */
    'docs.nav.panels': 'Panels',
    'docs.nav.tools': 'Toolbox {scripts}',
    'docs.nav.library': 'Library',
    'docs.nav.log': 'Release log',
    'docs.nav.install': 'Install · specs',

    /* ── 표지 ── */
    'docs.eyebrow': 'You Name It AE Plugin · v{version} · Windows · macOS',
    'docs.h1': 'Docs',
    'docs.lead': 'What the <b>{n} panels</b> do, what each of the <b>{scripts} tools</b> actually does, and what changed this time. <b>This page is for reading before you buy</b> — no login, no purchase.',

    /* ── 01 패널 ── */
    /* 🔴 판 제목은 Plate3(키 기반)라 `{n}` 을 못 채운다 — 개수는 표지 리드와 표 자체가 말한다. */
    'docs.panels.h': 'Panels',
    'docs.panels.tag': 'Open the ones you need from<br>Window ▸ Extensions in AE.',
    'docs.th.panel': 'Panel',
    'docs.th.what': 'What it is',
    'docs.th.does': 'What it does',
    'docs.panels.note': 'Panel names stay in English in either language — they are the strings you see in the AE menu.',

    'docs.panel.toolbox.k': 'One-click tool grid',
    'docs.panel.toolbox.d': 'Find one of the {scripts} tools by category, search or favourites, and press it. Hover a button and a 16-frame preview shows what that tool actually makes. Settings you have dialled in can be frozen into a button of your own.',
    'docs.panel.chat.k': 'Say it in plain language',
    'docs.panel.chat.d': 'Describe what you want and layers and keyframes land in the comp you have open. It runs on the Claude Code installed on your own machine, so it uses <b>your own Claude Pro/Max plan</b>. Anything that changes AE asks you first, and checkpoints take it back.',
    'docs.panel.library.k': 'Catalogue, five tabs',
    'docs.panel.library.d': 'Text presets · motion · effects · gradients · assets. Entrance and exit presets go on <b>separately</b>, timed with timeline markers. After they land you keep tuning them from the Effect Controls sliders, and re-applying never overwrites the values you set.',
    'docs.panel.curves.k': 'Bezier easing editor',
    'docs.panel.curves.d': 'Drag the handles or type the numbers. It reads the easing currently on an AE keyframe so you can put the same feel somewhere else. {curves} built-in curves plus your own.',
    'docs.panel.expressions.k': 'Expression editor',
    'docs.panel.expressions.d': '{expressions} built-in snippets in 11 groups. Edit the code and it applies itself 0.6s later, so there is no toggling off and on to check.',
    'docs.panel.custom-1.k': 'A grid you lay out yourself',
    'docs.panel.custom-1.d': 'Pick only what you use and put it where you want it. Not just tools — gradients, text presets, expressions, effects and curves share the same grid. Save several layouts, switch between them from a dropdown, pass them around as files.',
    'docs.panel.support.k': 'License · updates',
    'docs.panel.support.d': 'Activate and release the key, in-app updates (downloaded and installed), language switch, third-party notices. This is the one panel that sits outside the license gate.',

    /* ── 02 툴박스 ── */
    'docs.tools.h': 'Toolbox {scripts}',
    'docs.tools.tag': 'Hover a plate and the thing<br>that tool makes starts running.',
    'docs.tools.lead': 'The previews below are not mock-ups — they are <b>16 frames rendered in real After Effects</b>. Same image the panel puts above the button, re-baked whenever the tool changes.',
    'docs.tools.n': '{n} tools',
    'docs.noimg': 'Diagram',
    'docs.cat.motion': 'Motion',
    'docs.cat.motion.s': 'keyframes · easing · rigs',
    'docs.cat.layer': 'Layer',
    'docs.cat.layer.s': 'anchors · splitting · tracking',
    'docs.cat.comp': 'Comp',
    'docs.cat.comp.s': 'duration · tidying · precomps',
    'docs.cat.shape': 'Shape',
    'docs.cat.shape.s': 'paths · grids · patterns',
    'docs.cat.stylize': 'Stylize',
    'docs.cat.stylize.s': 'shadows · glitch · typing',
    'docs.cat.export': 'Export',
    'docs.cat.export.s': 'proxies · GIF · capture',
    /* 🔴 512 는 넓은 컴프에서의 숫자다. 구매자가 밟을 자리라 여기 적어 둔다 —
       근거 = 플러그인 `src/utils/patternMath.ts` `applyColumnsClamp` (셀 하한 4px). */
    'docs.note.patternLab': 'On Pattern Lab: the 512-column ceiling is a wide-comp number. A cell never goes under 4px, so at 1920 wide it folds back to 480 and the panel says so. 512 stands whole from 2048 wide up. Column count squares the shape count — try a small value first when you go dense.',

    /* ── 03 라이브러리 ── */
    'docs.lib.h': 'Library',
    'docs.lib.tag': 'The catalogue is a seed, not a ceiling.',
    'docs.lib.motion.n': '{motion}',
    'docs.lib.motion.t': 'Motion presets',
    'docs.lib.motion.d': 'Position · Rotate · Scale · Mix. All baked on spring physics',
    'docs.lib.text.n': '{textPresets}',
    'docs.lib.text.t': 'Text presets',
    'docs.lib.text.d': 'Including 4 that animate variable-font axes (weight, width, slant)',
    'docs.lib.grad.n': '{gradients}',
    'docs.lib.grad.t': 'Gradients',
    'docs.lib.grad.d': '8 packs. Multi-stop through the shape gradient fill',
    'docs.lib.curve.n': '{curves}',
    'docs.lib.curve.t': 'Easing curves',
    'docs.lib.curve.d': 'Read, edit and save them in the Curves panel',
    'docs.lib.expr.n': '{expressions}',
    'docs.lib.expr.t': 'Expressions',
    'docs.lib.expr.d': '11 groups. Live preview applies as you edit',
    'docs.lib.fx.n': '{effects}',
    'docs.lib.fx.t': 'Effect presets',
    'docs.lib.fx.d': 'What ships. These five, below',
    'docs.lib.mine.n': '∞',
    'docs.lib.mine.t': 'Yours',
    'docs.lib.mine.d': 'Capture an effect stack off a comp, keep it as your own preset, pass it around as a pack',
    'docs.lib.lang.n': '2',
    'docs.lib.lang.t': 'Languages',
    'docs.lib.lang.d': 'English · 한국어',

    /* 🔴 이펙트 이름은 로케일 무관이라 en/ko 가 같은 문자열이다(둘 다 적는 건 키 수를 맞추기 위함). */
    'docs.fx.riso-print': 'Riso Print',
    'docs.fx.riso-print.d': 'Riso ink bleed and paper tooth, as real texture',
    'docs.fx.chromatic-aberration': 'Chromatic Aberration',
    'docs.fx.chromatic-aberration.d': 'Colour fringing at the edges',
    'docs.fx.crt-screen': 'CRT Screen',
    'docs.fx.crt-screen.d': 'Scanlines · screen curvature',
    'docs.fx.confetti-vector': 'Confetti',
    'docs.fx.confetti-vector.d': 'Vector confetti',
    'docs.fx.vox-original': 'Infographic',
    'docs.fx.vox-original.d': 'Infographic typesetting treatment',

    /* ── 04 업데이트 로그 ── */
    'docs.log.h': 'Release log',
    'docs.log.tag': 'Minor updates are free.<br>You get them inside the panel.',
    'docs.log.n': '{n} items',

    /* ── 설치 · 사양 ── */
    'docs.install.h': 'Install · specs',
    'docs.spec.price.k': 'Price',
    'docs.spec.price.v': '{price} USD',
    'docs.spec.price.n': 'Pay once · excl. tax · Polar',
    'docs.spec.host.k': 'Host app',
    'docs.spec.host.v': 'After Effects 2022 and newer',
    'docs.spec.host.n': 'Window ▸ Extensions ▸ You Name It',
    'docs.spec.form.k': 'Install',
    'docs.spec.form.v': 'ZXP extension',
    'docs.spec.form.n': 'Once, through a ZXP installer',
    'docs.spec.os.k': 'Operating system',
    'docs.spec.os.v': 'Windows · macOS',
    'docs.spec.os.n': 'Depth Pass runs on Apple Silicon and Windows GPUs only',
    'docs.spec.license.k': 'License',
    'docs.spec.license.v': '2 machines · 1 person',
    'docs.spec.license.n': 'Release a machine yourself from the customer portal',
    'docs.spec.lang.k': 'Language',
    'docs.spec.lang.v': 'English · 한국어',
    'docs.spec.lang.n': 'Switch inside the panel',
    'docs.spec.net.k': 'Network',
    'docs.spec.net.v': 'Checks every 7 days',
    'docs.spec.net.n': 'Up to 30 days offline · Chat needs a connection',
    'docs.spec.support.k': 'Support',
    'docs.spec.support.v': 'support@younameit.works',
    'docs.spec.support.n': 'Update notices · install help',

    'docs.cta.txt': 'That is everything there is to read.',
    'docs.cta.btn': 'Get it — {price}',
  },

  ko: {
    'docs.nav.panels': '패널',
    'docs.nav.tools': '툴박스 {scripts}',
    'docs.nav.library': '라이브러리',
    'docs.nav.log': '업데이트 로그',
    'docs.nav.install': '설치 · 사양',

    'docs.eyebrow': 'You Name It AE Plugin · v{version} · Windows · macOS',
    'docs.h1': 'Docs',
    'docs.lead': '패널 <b>{n}개</b>가 무엇을 하는지, 툴 <b>{scripts}개</b>가 각각 무슨 일을 하는지, 그리고 이번에 무엇이 바뀌었는지. <b>사기 전에 읽어도 되는 면</b>입니다 — 로그인도 구매도 필요 없습니다.',

    'docs.panels.h': '패널',
    'docs.panels.tag': 'AE 창 메뉴 ▸ Extensions 에서<br>필요한 것만 띄웁니다.',
    'docs.th.panel': '패널',
    'docs.th.what': '정체',
    'docs.th.does': '하는 일',
    'docs.panels.note': '패널 이름은 로케일과 무관하게 영문입니다 — AE 메뉴에 뜨는 문자열과 같습니다.',

    'docs.panel.toolbox.k': '원클릭 도구 그리드',
    'docs.panel.toolbox.d': '툴 {scripts}개를 카테고리·검색·즐겨찾기로 찾아 누릅니다. 버튼 위에 마우스를 올리면 그 툴이 실제로 무엇을 만드는지 16프레임 미리보기가 뜹니다. 한 번 맞춘 설정은 굳혀서 내 버튼으로 만들 수 있습니다.',
    'docs.panel.chat.k': '자연어로 구현을 맡기는 패널',
    'docs.panel.chat.d': '원하는 걸 문장으로 설명하면 지금 열려 있는 컴프에 레이어와 키프레임이 생깁니다. 당신 컴퓨터에 설치된 Claude Code 로 돌아가므로 <b>당신의 Claude Pro/Max 구독</b>을 씁니다. AE 를 바꾸는 동작은 매번 승인 창이 뜨고, 체크포인트로 되돌릴 수 있습니다.',
    'docs.panel.library.k': '카탈로그 5탭',
    'docs.panel.library.d': '텍스트 프리셋 · 모션 · 이펙트 · 그라디언트 · 에셋. 등장과 퇴장 프리셋을 <b>각각</b> 걸고 타임라인 마커로 타이밍을 잡습니다. 적용 뒤에도 Effect Controls 슬라이더로 계속 만지고, 다시 적용해도 당신이 맞춘 값을 덮지 않습니다.',
    'docs.panel.curves.k': '베지어 이징 에디터',
    'docs.panel.curves.d': '핸들을 끌거나 숫자를 칩니다. AE 키프레임에서 지금 걸린 이징을 읽어 와 다른 곳에 그대로 붙일 수 있습니다. 빌트인 커브 {curves}개 + 내 커브 저장.',
    'docs.panel.expressions.k': '익스프레션 에디터',
    'docs.panel.expressions.d': '빌트인 스니펫 {expressions}개를 11개 묶음으로. 코드를 고치면 0.6초 뒤 자동 적용되므로 껐다 켜며 확인할 필요가 없습니다.',
    'docs.panel.custom-1.k': '내가 짜는 격자',
    'docs.panel.custom-1.d': '쓰는 것만 골라 원하는 자리에 놓습니다. 툴뿐 아니라 그라디언트·텍스트 프리셋·익스프레션·이펙트·커브를 같은 격자에 섞습니다. 배치를 여러 개 저장해 드롭다운으로 갈아 끼우고 파일로 주고받습니다.',
    'docs.panel.support.k': '라이선스 · 업데이트',
    'docs.panel.support.d': '키 활성/해제, 인앱 업데이트(받아서 설치까지), 언어 전환, 서드파티 고지. 이 패널만 라이선스 게이트 밖에 있습니다.',

    'docs.tools.h': '툴박스 {scripts}',
    'docs.tools.tag': '판 위에 마우스를 올리면<br>그 툴이 실제로 만드는 것이 돕니다.',
    'docs.tools.lead': '아래 미리보기는 목업이 아닙니다 — <b>실제 After Effects 에서 렌더한 16프레임</b>입니다. 패널이 버튼 위에 띄우는 것과 같은 그림이고, 툴을 고치면 다시 굽습니다.',
    'docs.tools.n': '{n}개',
    'docs.noimg': '프리뷰 도해',
    'docs.cat.motion': '모션',
    'docs.cat.motion.s': '키프레임 · 이징 · 리그',
    'docs.cat.layer': '레이어',
    'docs.cat.layer.s': '앵커 · 분해 · 추적',
    'docs.cat.comp': '컴프',
    'docs.cat.comp.s': '길이 · 정리 · 프리컴프',
    'docs.cat.shape': '셰이프',
    'docs.cat.shape.s': '패스 · 격자 · 패턴',
    'docs.cat.stylize': '스타일',
    'docs.cat.stylize.s': '그림자 · 글리치 · 타이핑',
    'docs.cat.export': '내보내기',
    'docs.cat.export.s': '프록시 · GIF · 캡처',
    'docs.note.patternLab': 'Pattern Lab 한 가지: 가로 칸 수 상한 512 는 컴프가 넓을 때의 값입니다. 셀 한 칸이 4px 밑으로 내려가지 않게 잡혀 있어서 1920 폭에서는 480 에서 접히고, 패널이 접혔다고 알려줍니다. 512 가 온전히 서려면 컴프 폭이 2048 이상이어야 합니다. 칸 수를 올리면 도형 수가 제곱으로 늘어나니, 촘촘하게 쓰실 때는 작은 값으로 먼저 확인해 보세요.',

    'docs.lib.h': '라이브러리',
    'docs.lib.tag': '카탈로그는 상한이 아니라 씨앗입니다.',
    'docs.lib.motion.n': '{motion}',
    'docs.lib.motion.t': '모션 프리셋',
    'docs.lib.motion.d': 'Position · Rotate · Scale · Mix. 전부 스프링 물리로 구워집니다',
    'docs.lib.text.n': '{textPresets}',
    'docs.lib.text.t': '텍스트 프리셋',
    'docs.lib.text.d': '가변 폰트 축(굵기·너비·기울기) 애니메이션 4종 포함',
    'docs.lib.grad.n': '{gradients}',
    'docs.lib.grad.t': '그라디언트',
    'docs.lib.grad.d': '8개 묶음. 셰이프 그라디언트 필로 다색 지원',
    'docs.lib.curve.n': '{curves}',
    'docs.lib.curve.t': '이징 커브',
    'docs.lib.curve.d': 'Curves 패널에서 읽고 고치고 저장합니다',
    'docs.lib.expr.n': '{expressions}',
    'docs.lib.expr.t': '익스프레션',
    'docs.lib.expr.d': '11개 묶음. Live Preview 로 고치는 즉시 적용',
    'docs.lib.fx.n': '{effects}',
    'docs.lib.fx.t': '이펙트 프리셋',
    'docs.lib.fx.d': '출고분. 아래가 그 다섯입니다',
    'docs.lib.mine.n': '∞',
    'docs.lib.mine.t': '내가 만든 것',
    'docs.lib.mine.d': '컴프의 이펙트 스택을 캡처해 내 프리셋으로 저장하고 팩으로 주고받습니다',
    'docs.lib.lang.n': '2',
    'docs.lib.lang.t': '언어',
    'docs.lib.lang.d': '한국어 · English',

    'docs.fx.riso-print': 'Riso Print',
    'docs.fx.riso-print.d': '리소 인쇄의 잉크 번짐과 종이 결을 실제 텍스처로',
    'docs.fx.chromatic-aberration': 'Chromatic Aberration',
    'docs.fx.chromatic-aberration.d': '가장자리 색수차',
    'docs.fx.crt-screen': 'CRT Screen',
    'docs.fx.crt-screen.d': '주사선 · 화면 곡률',
    'docs.fx.confetti-vector': 'Confetti',
    'docs.fx.confetti-vector.d': '벡터 색종이',
    'docs.fx.vox-original': 'Infographic',
    'docs.fx.vox-original.d': '인포그래픽 조판 기법',

    'docs.log.h': '업데이트 로그',
    'docs.log.tag': '마이너 업데이트는 무료입니다.<br>패널 안에서 받아 설치합니다.',
    'docs.log.n': '{n}건',

    'docs.install.h': '설치 · 사양',
    'docs.spec.price.k': '가격',
    'docs.spec.price.v': '{price} USD',
    'docs.spec.price.n': '일회 구매 · 세금 별도 · Polar',
    'docs.spec.host.k': '호스트 앱',
    'docs.spec.host.v': 'After Effects 2022 이상',
    'docs.spec.host.n': 'AE 창 메뉴 ▸ Extensions ▸ You Name It',
    'docs.spec.form.k': '설치 형태',
    'docs.spec.form.v': 'ZXP 확장',
    'docs.spec.form.n': 'ZXP 설치 프로그램으로 한 번',
    'docs.spec.os.k': '운영체제',
    'docs.spec.os.v': 'Windows · macOS',
    'docs.spec.os.n': 'Depth Pass 는 Apple Silicon · Windows GPU 에서만',
    'docs.spec.license.k': '라이선스',
    'docs.spec.license.v': '2대 · 1인',
    'docs.spec.license.n': '기기 해제는 고객 포털에서 직접',
    'docs.spec.lang.k': '언어',
    'docs.spec.lang.v': '한국어 · English',
    'docs.spec.lang.n': '패널 안에서 전환',
    'docs.spec.net.k': '네트워크',
    'docs.spec.net.v': '7일마다 확인',
    'docs.spec.net.n': '오프라인 30일까지 · Chat 은 연결 필요',
    'docs.spec.support.k': '지원',
    'docs.spec.support.v': 'support@younameit.works',
    'docs.spec.support.n': '인앱 업데이트 알림 · 설치 안내',

    'docs.cta.txt': '읽을 건 다 읽으셨습니다.',
    'docs.cta.btn': '{price} · 구매하기',
  },
};

export default DOCS;
