/* `/ae/docs` 페이지 사전 — EN/KO. 🔴 이 파일은 **이 페이지 레인만** 고친다.
   말투·낱말·사실의 정본 = 플러그인 repo `donys/docs/VOICE_AND_TERMS.md` (KO 합니다체 · 단어장 §3 · 사실 §4).

   🔴 **툴 설명은 여기 없다.** 제품이 이미 양 로케일을 갖고 있고 `lib/docsData.ts` 가
   출고 태그에서 그걸 읽어 온다 — 여기에 손번역을 들이면 패널과 사이트가 다른 말을 하기 시작한다.
   패널·툴·이펙트 **이름**도 여기 적지 않는다(로케일 무관 영문). 예외는 `docs.fx.<slug>` —
   사이트 표기가 제품 표기와 갈라진 자리라 양 로케일에 **같은 문자열**을 적어 둔다.
   툴 카드에 붙는 **한 줄 추가**(`docs.note.<id>` — 돌아가는 환경·첫 다운로드·한계)만 여기 있다.
   그 id 가 출고 태그에 없으면 생성기가 빌드를 세운다(개명·은퇴 뒤 조용히 사라지지 않게).

   🔴 숫자는 자리표시자로: `{scripts}` 같은 건 `lib/copy.ts` 가 `lib/product.ts` 에서 채우고,
   `{n}` · `{panels}` · `{others}` · `{portal}` · `{notes}` 는 렌더 쪽에서 실제 값으로 채운다.
   사전에 숫자를 박으면 그 순간 낡는다.

   🔴 사양 8필드(`docs.spec.*`)는 `/ae` 사양(`ae.sp*`)과 **같은 사실·같은 낱말**이어야 한다.
   한쪽을 고치면 다른 쪽도 본다(두 벌인 이유 = 두 면이 서로 다른 레인이었다 — 한 벌로 합치는 건 남은 일). */
import type { Dict } from './types';

const DOCS: Dict = {
  en: {
    /* ── 목차 칩 (섹션 data-name 과 같은 키를 쓴다) ── */
    'docs.nav.panels': 'Panels',
    'docs.nav.tools': 'Toolbox {scripts}',
    'docs.nav.catalog': 'Catalog',
    'docs.nav.notes': 'Release notes',
    'docs.nav.install': 'Install · specs',

    /* ── 표지 ── */
    'docs.eyebrow': 'You Name It AE Plugin · v{version} · Windows · macOS',
    'docs.h1': 'Docs',
    'docs.lead': 'What each of the <b>{n} panels</b> and <b>{scripts} tools</b> does, what it needs to run, how to install it, and what changed most recently. It is here to read before you buy, and to keep open while you work.',

    /* ── 01 패널 ── */
    'docs.panels.h': 'Panels',
    'docs.panels.tag': 'Each one is its own entry under<br>Window ▸ Extensions in After Effects.',
    'docs.th.panel': 'Panel',
    'docs.th.what': 'What it is',
    'docs.th.does': 'What it does',
    /* 영문 독자에게 "패널 이름은 영문" 은 정보가 아니다 — 국문 면에서만 뜬다(빈 값이면 렌더 안 함). */
    'docs.panels.note': '',

    'docs.panel.toolbox.k': 'One-click tool grid',
    'docs.panel.toolbox.d': 'Find one of the {scripts} tools by category or search, and press it. Hover a button and a 16-frame preview shows what that tool actually makes. The settings you last ran can be saved as a button of your own.',
    'docs.panel.chat.k': 'Say it in plain language',
    'docs.panel.chat.d': 'Describe what you want and layers and keyframes land in the comp you have open. It runs on <b>Claude Code</b> or <b>Codex</b>, installed on your computer and signed in with <b>your own plan</b> — Claude Pro or Max, or ChatGPT — and it needs an internet connection. The plan is not included in the price. Anything that changes AE asks you first, and checkpoints take it back.',
    'docs.panel.library.k': 'Catalog, five tabs',
    'docs.panel.library.d': 'Text presets · motion · effects · gradients · assets. In and Out presets go on <b>separately</b>, timed with timeline markers. After they land you keep tuning them from the Effect Controls sliders, and re-applying never overwrites the values you set. Assets holds your own files, plus free image, GIF and sound search with your own API keys.',
    'docs.panel.curves.k': 'Bezier easing editor',
    'docs.panel.curves.d': 'Drag the handles or type the numbers. It reads the easing currently on an AE keyframe so you can put the same feel somewhere else. {curves} built-in curves plus your own.',
    'docs.panel.expressions.k': 'Expression editor',
    'docs.panel.expressions.d': '{expressions} built-in snippets in 10 groups, plus a Custom tab for your own. With Live Preview on, an edit applies itself 0.6s later, so there is no toggling off and on to check.',
    'docs.panel.custom-1.k': 'A grid you lay out yourself',
    'docs.panel.custom-1.d': 'Pick only what you use and put it where you want it. Not just tools — gradients, text presets, expressions, effects and curves share the same grid. Save several layouts, switch between them from a dropdown, pass them around as files.',
    'docs.panel.support.k': 'License · updates',
    'docs.panel.support.d': 'Activate or deactivate this computer, in-app updates (downloaded and installed), language, third-party notices. The one panel that opens without a license — the key goes in here.',

    /* ── 02 툴박스 ── */
    'docs.tools.h': 'Toolbox {scripts}',
    'docs.tools.tag': 'Hover or tap a plate —<br>it plays what the tool makes.',
    'docs.tools.lead': 'The previews below are not mock-ups — they are <b>16 frames rendered in real After Effects</b>. Same image the panel puts above the button, re-baked whenever the tool changes.',
    'docs.tools.n': '{n} tools',
    'docs.noimg': 'No preview',
    'docs.cat.motion': 'Motion',
    'docs.cat.motion.s': 'keyframes · easing · rigs',
    'docs.cat.layer': 'Layer',
    'docs.cat.layer.s': 'anchors · splitting · tracking',
    'docs.cat.comp': 'Comp',
    'docs.cat.comp.s': 'duration · tidying · precomps',
    'docs.cat.shape': 'Shape',
    'docs.cat.shape.s': 'paths · grids · patterns',
    'docs.cat.stylize': 'Stylize',
    'docs.cat.stylize.s': 'shadows · glitch · typing',
    'docs.cat.export': 'Export',
    'docs.cat.export.s': 'proxies · GIF · capture',
    /* 툴 카드 한 줄 추가 — 그 카드 밑에 뜬다. 근거:
       depthPass    = 인텔 맥만 막힌다(`depthSupport.ts` DP_NO_INTEL_MAC) · 윈도는 GPU 가 없거나 불합격이면 CPU 로 돈다
                      (`sidecar/depth/ort.mjs` dml→cpu) · 첫 사용 다운로드 = 모델 59.3MB + 런타임 49.8(mac)/52.9(win)MB
                      (`dl.younameit.works/depth/manifest.json`, 패널도 1e6 MB 로 센다)
       gifConverter = `binMissing` "~80MB" — 받기 전에 묻는다
       patternLab   = `patternMath.ts` `applyColumnsClamp` (셀 하한 4px) */
    'docs.note.depthPass': 'Runs on Apple Silicon Macs and on Windows — not on Intel Macs. The first run downloads about 110 MB, once.',
    'docs.note.gifConverter': 'The first run asks before it downloads FFmpeg and Gifsicle (about 80 MB), once.',
    'docs.note.patternLab': 'Columns reach 512 on comps 2048 px wide or more (480 at 1920). Shape count grows with the square of the columns.',

    /* ── 03 카탈로그 — 🔴 칸마다 **어느 패널에 있는지** 적는다(Curves·Expressions 는 Library 가 아니다) ── */
    'docs.catalog.h': 'Catalog',
    'docs.catalog.tag': 'The catalog is a seed, not a ceiling.',
    'docs.lib.motion.n': '{motion}',
    'docs.lib.motion.t': 'Motion presets',
    'docs.lib.motion.d': 'Library ▸ Motion. Position · Rotate · Scale · Mix, all baked on spring physics',
    'docs.lib.text.n': '{textPresets}',
    'docs.lib.text.t': 'Text presets',
    'docs.lib.text.d': 'Library ▸ Text Preset. Including 4 that animate variable-font axes (weight, width, slant)',
    'docs.lib.grad.n': '{gradients}',
    'docs.lib.grad.t': 'Gradients',
    'docs.lib.grad.d': 'Library ▸ Gradient. 8 packs, multi-stop through the shape gradient fill',
    'docs.lib.fx.n': '{effects}',
    'docs.lib.fx.t': 'Effect presets',
    'docs.lib.fx.d': 'Library ▸ Effects. Built in — these five, below',
    'docs.lib.curve.n': '{curves}',
    'docs.lib.curve.t': 'Easing curves',
    'docs.lib.curve.d': 'Curves panel. Read, edit and save them there',
    'docs.lib.expr.n': '{expressions}',
    'docs.lib.expr.t': 'Expressions',
    'docs.lib.expr.d': 'Expressions panel. 10 built-in groups, plus a Custom tab for yours',
    'docs.lib.mine.n': '+',
    'docs.lib.mine.t': 'Yours',
    'docs.lib.mine.d': 'Capture an effect stack off a comp, keep it as your own preset, pass it around as a pack',

    /* 🔴 이펙트 이름은 로케일 무관이라 en/ko 가 같은 문자열이다(둘 다 적는 건 키 수를 맞추기 위함). */
    'docs.fx.riso-print': 'Riso Print',
    'docs.fx.riso-print.d': 'Riso ink bleed and paper tooth, as real texture',
    'docs.fx.chromatic-aberration': 'Chromatic Aberration',
    'docs.fx.chromatic-aberration.d': 'Color fringing at the edges',
    'docs.fx.crt-screen': 'CRT Screen',
    'docs.fx.crt-screen.d': 'Scanlines · screen curvature',
    'docs.fx.confetti-vector': 'Confetti',
    'docs.fx.confetti-vector.d': 'Vector confetti',
    'docs.fx.vox-original': 'Infographic',
    'docs.fx.vox-original.d': 'Infographic typesetting treatment',

    /* ── 04 릴리스 노트 — 🔴 정본은 `/update` 다(패널의 `What's new · manual install` 이 거기로 간다).
       여기는 최신 한 판만 싣고 나머지는 `/update` 로 넘긴다 — 같은 로그가 두 면에 전량 있으면 정본이 둘이다. ── */
    'docs.notes.h': 'Release notes',
    'docs.notes.tag': 'Minor updates are free and arrive inside the panel.<br>A major version may be a paid upgrade.',
    'docs.notes.n': '{n} items',
    'docs.notes.all': 'All {n} release notes · manual download →',

    /* ── 05 설치 — 🔴 앵커 `#install` 은 `/ae` 히어로·FAQ·사양·푸터·결제 뒤 이동이 가리킨다. 이름 바꾸지 마라.
       사실 근거: VOICE_AND_TERMS §4 · INSTALL_GUIDE.md (방법 2·안 될 때) · 태그 i18n `support.*`.
       ⚠️ 1단계 "주문 메일로 온다" 는 Polar 혜택(키·파일) 전달 방식에서 옮긴 것이다 — 메일 문면은 오너 확인 전. ── */
    'docs.install.h': 'Install',
    'docs.install.tag': 'Three steps,<br>once per computer.',
    'docs.step1.t': 'Get the file and the key',
    'docs.step1.d': 'Polar sends your license key and the installer (.zxp) to your order email. Both stay in the <a href="{portal}" target="_blank" rel="noopener">customer portal</a> — sign in there with the email you paid with.',
    'docs.step2.t': 'Install',
    'docs.step2.d': 'Quit After Effects, then drop the .zxp on the free <a href="https://aescripts.com/learn/zxp-installer/" target="_blank" rel="noopener">ZXP Installer</a>. It may warn that the certificate is self-signed — we sign the file ourselves, so carry on.',
    'docs.step3.t': 'Activate',
    'docs.step3.d': 'Open After Effects and go to <b>Window ▸ Extensions ▸ You Name It - Support</b>. Paste the key and press Activate — the other {others} panels unlock straight away.',
    'docs.install.menu': 'Every panel is its own entry in that menu:',
    'docs.upd.h': 'Updating',
    'docs.upd.d': 'When a new version is out, the Support panel shows it. Press Update now, then restart After Effects — a panel cannot replace itself while it is running. If the in-panel install fails, the manual download is on the <a href="{notes}">release notes page</a>.',
    'docs.hand.h': 'Installing by hand',
    'docs.hand.d': 'With After Effects closed, rename the .zxp to .zip, unzip it, and put the folder in the place below, named exactly <code>com.donys.plugin.cep</code> — any other name, especially one with an apostrophe, leaves the panels loading forever. Do not add or remove a single file: the contents must match the signature, or the panels open blank. If you unzipped over an older copy, delete the folder and unzip again.',
    'docs.rm.h': 'Removing it',
    'docs.rm.d': 'Deactivate this computer in the Support panel first — otherwise its seat stays taken. Then remove it in ZXP Installer, or delete the <code>com.donys.plugin.cep</code> folder. If that computer is already gone, deactivate it in the <a href="{portal}" target="_blank" rel="noopener">customer portal</a>.',
    'docs.fix.h': 'If it does not work',
    'docs.fix.list': [
      'The panel opens blank — the files do not match the signature, usually leftovers from an older version. Delete the folder and install again.',
      'It keeps loading — the folder is not named <code>com.donys.plugin.cep</code>. Rename it.',
      'Nothing under Window ▸ Extensions — After Effects is older than 2022, or the folder is in the wrong place. Check the path above.',
      'The update says it has no write permission — it is installed for all users. Install the .zxp again as an administrator, or by hand into your user folder.',
    ],
    'docs.fix.mail': 'Still stuck? Email <a href="mailto:support@younameit.works">support@younameit.works</a> with this file attached — Windows <code>%TEMP%\\donys-update.log</code> · macOS <code>$TMPDIR/donys-update.log</code>.',

    /* ── 사양 8필드 — `/ae` 의 `ae.sp*` 와 같은 사실·같은 낱말(위 머리말) ── */
    'docs.spec.h': 'Specs',
    'docs.spec.price.k': 'Price',
    'docs.spec.price.v': '{price} USD',
    'docs.spec.price.n': 'One-time · tax depends on your country, shown at checkout · Polar',
    'docs.spec.host.k': 'Host app',
    'docs.spec.host.v': 'After Effects 2022 or newer',
    'docs.spec.host.n': 'Window ▸ Extensions ▸ the {panels} "You Name It - …" entries',
    'docs.spec.form.k': 'Install',
    'docs.spec.form.v': 'ZXP extension',
    'docs.spec.form.n': 'Free ZXP Installer, or by hand — <a href="#install">install guide</a>',
    'docs.spec.os.k': 'Operating system',
    'docs.spec.os.v': 'Windows · macOS',
    'docs.spec.os.n': 'Depth Pass runs on Apple Silicon Macs and on Windows — not on Intel Macs',
    'docs.spec.license.k': 'License',
    'docs.spec.license.v': '2 computers · 1 person',
    'docs.spec.license.n': 'Deactivate a computer yourself — in the Support panel or the <a href="{portal}" target="_blank" rel="noopener">customer portal</a>',
    'docs.spec.lang.k': 'Language',
    'docs.spec.lang.v': '한국어 · English',
    'docs.spec.lang.n': 'Switch it inside the panel',
    'docs.spec.net.k': 'Network',
    'docs.spec.net.v': 'Checks in every 7 days',
    'docs.spec.net.n': 'Up to 30 days offline · Chat needs a connection',
    'docs.spec.support.k': 'Support',
    'docs.spec.support.v': '<a href="mailto:support@younameit.works">support@younameit.works</a>',
    'docs.spec.support.n': 'Install, license and refund questions · we aim to reply within 48 hours on business days',

    /* ── 끝 — 🔴 이 페이지의 CTA 는 여기 하나다(구매). 버튼 라벨은 사이트 공통 `s.buy.price`. ── */
    'docs.cta.txt': 'Refunds, the Chat plan, two computers — what people ask before buying is answered on the product page.',
    'docs.cta.faq': 'Common questions →',
  },

  ko: {
    'docs.nav.panels': '패널',
    'docs.nav.tools': 'Toolbox {scripts}',
    'docs.nav.catalog': '카탈로그',
    'docs.nav.notes': '업데이트 노트',
    'docs.nav.install': '설치 · 사양',

    'docs.eyebrow': 'You Name It AE Plugin · v{version} · Windows · macOS',
    'docs.h1': 'Docs',
    'docs.lead': '패널 <b>{n}개</b>와 툴 <b>{scripts}개</b>가 각각 무엇을 하고 무엇이 있어야 도는지, 어떻게 설치하는지, 최근에 무엇이 바뀌었는지 적었습니다. 사기 전에 읽어도 되고, 작업하면서 열어 두어도 됩니다.',

    'docs.panels.h': '패널',
    'docs.panels.tag': 'After Effects 의 Window ▸ Extensions 에<br>패널마다 항목이 하나씩 있습니다.',
    'docs.th.panel': '패널',
    'docs.th.what': '무엇인가',
    'docs.th.does': '하는 일',
    'docs.panels.note': '패널 이름은 로케일과 무관하게 영문입니다 — AE 메뉴에 뜨는 문자열과 같습니다.',

    'docs.panel.toolbox.k': '원클릭 툴 그리드',
    'docs.panel.toolbox.d': '툴 {scripts}개를 카테고리나 검색으로 찾아 누릅니다. 버튼 위에 마우스를 올리면 그 툴이 실제로 무엇을 만드는지 16프레임 미리보기가 뜹니다. 마지막에 돌린 설정은 내 버튼으로 저장할 수 있습니다.',
    'docs.panel.chat.k': '자연어로 구현을 맡기는 패널',
    'docs.panel.chat.d': '원하는 걸 문장으로 설명하면 지금 열려 있는 컴프에 레이어와 키프레임이 생깁니다. 당신 컴퓨터에 설치한 <b>Claude Code</b> 또는 <b>Codex</b> 로 돌아가고, <b>당신의 구독</b>(Claude Pro·Max 또는 ChatGPT)과 인터넷 연결이 필요합니다. 구독료는 가격에 포함되지 않습니다. AE 를 바꾸는 동작은 매번 먼저 묻고, 체크포인트로 되돌릴 수 있습니다.',
    'docs.panel.library.k': '카탈로그 5탭',
    'docs.panel.library.d': '텍스트 프리셋 · 모션 · 이펙트 · 그라디언트 · 에셋. 등장과 퇴장 프리셋을 <b>각각</b> 걸고 타임라인 마커로 타이밍을 잡습니다. 적용 뒤에도 Effect Controls 슬라이더로 계속 만지고, 다시 적용해도 당신이 맞춘 값을 덮지 않습니다. 에셋 탭에는 내 파일과, 본인 API 키로 여는 무료 이미지·GIF·사운드 검색이 있습니다.',
    'docs.panel.curves.k': '베지어 이징 에디터',
    'docs.panel.curves.d': '핸들을 끌거나 숫자를 칩니다. AE 키프레임에서 지금 걸린 이징을 읽어 와 다른 곳에 그대로 붙일 수 있습니다. 빌트인 커브 {curves}개 + 내 커브 저장.',
    'docs.panel.expressions.k': '익스프레션 에디터',
    'docs.panel.expressions.d': '빌트인 스니펫 {expressions}개를 10개 묶음으로, 그리고 내 것을 담는 Custom 탭. Live Preview 를 켜 두면 코드를 고친 뒤 0.6초 만에 적용되므로 껐다 켜며 확인할 필요가 없습니다.',
    'docs.panel.custom-1.k': '내가 짜는 격자',
    'docs.panel.custom-1.d': '쓰는 것만 골라 원하는 자리에 놓습니다. 툴뿐 아니라 그라디언트·텍스트 프리셋·익스프레션·이펙트·커브를 같은 격자에 섞습니다. 배치를 여러 개 저장해 드롭다운으로 갈아 끼우고 파일로 주고받습니다.',
    'docs.panel.support.k': '라이선스 · 업데이트',
    'docs.panel.support.d': '이 컴퓨터의 활성화 · 활성화 해제, 인앱 업데이트(받아서 설치까지), 언어 전환, 서드파티 고지. 라이선스 없이 열리는 유일한 패널이고, 키는 여기에 넣습니다.',

    'docs.tools.h': 'Toolbox {scripts}',
    'docs.tools.tag': '판에 마우스를 올리거나 탭하면<br>그 툴이 만드는 것이 돕니다.',
    'docs.tools.lead': '아래 미리보기는 목업이 아닙니다 — <b>실제 After Effects 에서 렌더한 16프레임</b>입니다. 패널이 버튼 위에 띄우는 것과 같은 그림이고, 툴을 고치면 다시 굽습니다.',
    'docs.tools.n': '{n}개',
    'docs.noimg': '미리보기 없음',
    'docs.cat.motion': '모션',
    'docs.cat.motion.s': '키프레임 · 이징 · 리그',
    'docs.cat.layer': '레이어',
    'docs.cat.layer.s': '앵커 · 분해 · 추적',
    'docs.cat.comp': '컴프',
    'docs.cat.comp.s': '길이 · 정리 · 프리컴프',
    'docs.cat.shape': '셰이프',
    'docs.cat.shape.s': '패스 · 격자 · 패턴',
    'docs.cat.stylize': '스타일',
    'docs.cat.stylize.s': '그림자 · 글리치 · 타이핑',
    'docs.cat.export': '내보내기',
    'docs.cat.export.s': '프록시 · GIF · 캡처',
    'docs.note.depthPass': 'Apple Silicon Mac 과 Windows 에서 돕니다 — 인텔 Mac 에서는 돌지 않습니다. 처음 쓸 때 약 110MB 를 한 번 내려받습니다.',
    'docs.note.gifConverter': '처음 쓸 때 FFmpeg·Gifsicle(약 80MB)을 받을지 먼저 묻고, 한 번만 받습니다.',
    'docs.note.patternLab': '가로 칸은 컴프 폭 2048px 이상에서 512 까지 갑니다(1920 폭은 480). 도형 수는 칸 수의 제곱으로 늘어납니다.',

    'docs.catalog.h': '카탈로그',
    'docs.catalog.tag': '카탈로그는 상한이 아니라 씨앗입니다.',
    'docs.lib.motion.n': '{motion}',
    'docs.lib.motion.t': '모션 프리셋',
    'docs.lib.motion.d': 'Library ▸ Motion. Position · Rotate · Scale · Mix, 전부 스프링 물리로 구워집니다',
    'docs.lib.text.n': '{textPresets}',
    'docs.lib.text.t': '텍스트 프리셋',
    'docs.lib.text.d': 'Library ▸ Text Preset. 가변 폰트 축(굵기·너비·기울기) 애니메이션 4종 포함',
    'docs.lib.grad.n': '{gradients}',
    'docs.lib.grad.t': '그라디언트',
    'docs.lib.grad.d': 'Library ▸ Gradient. 8개 묶음, 셰이프 그라디언트 필로 다색 지원',
    'docs.lib.fx.n': '{effects}',
    'docs.lib.fx.t': '이펙트 프리셋',
    'docs.lib.fx.d': 'Library ▸ Effects. 기본 제공 — 아래 다섯 가지입니다',
    'docs.lib.curve.n': '{curves}',
    'docs.lib.curve.t': '이징 커브',
    'docs.lib.curve.d': 'Curves 패널. 거기서 읽고 고치고 저장합니다',
    'docs.lib.expr.n': '{expressions}',
    'docs.lib.expr.t': '익스프레션',
    'docs.lib.expr.d': 'Expressions 패널. 빌트인 10개 묶음, 그리고 내 것을 담는 Custom 탭',
    'docs.lib.mine.n': '+',
    'docs.lib.mine.t': '내가 만든 것',
    'docs.lib.mine.d': '컴프의 이펙트 스택을 캡처해 내 프리셋으로 저장하고 팩으로 주고받습니다',

    'docs.fx.riso-print': 'Riso Print',
    'docs.fx.riso-print.d': '리소 인쇄의 잉크 번짐과 종이 결을 실제 텍스처로',
    'docs.fx.chromatic-aberration': 'Chromatic Aberration',
    'docs.fx.chromatic-aberration.d': '가장자리 색수차',
    'docs.fx.crt-screen': 'CRT Screen',
    'docs.fx.crt-screen.d': '주사선 · 화면 곡률',
    'docs.fx.confetti-vector': 'Confetti',
    'docs.fx.confetti-vector.d': '벡터 색종이',
    'docs.fx.vox-original': 'Infographic',
    'docs.fx.vox-original.d': '인포그래픽 조판 기법',

    'docs.notes.h': '업데이트 노트',
    'docs.notes.tag': '마이너 업데이트는 무료이고 패널 안으로 들어옵니다.<br>메이저 버전은 유료 업그레이드일 수 있습니다.',
    'docs.notes.n': '{n}건',
    'docs.notes.all': '업데이트 노트 {n}건 전부 · 수동 다운로드 →',

    'docs.install.h': '설치',
    'docs.install.tag': '컴퓨터마다 한 번,<br>세 단계.',
    'docs.step1.t': '파일과 키 받기',
    'docs.step1.d': 'Polar 가 라이선스 키와 설치 파일(.zxp)을 구매 메일로 보냅니다. 둘 다 <a href="{portal}" target="_blank" rel="noopener">고객 포털</a>에도 남아 있고, 결제한 메일 주소로 로그인하면 됩니다.',
    'docs.step2.t': '설치',
    'docs.step2.d': 'After Effects 를 닫고, 무료 <a href="https://aescripts.com/learn/zxp-installer/" target="_blank" rel="noopener">ZXP Installer</a> 에 .zxp 파일을 끌어다 놓습니다. 자체 서명 인증서라는 경고가 뜰 수 있습니다 — 파일을 우리가 직접 서명해서 그렇고, 그대로 진행하면 됩니다.',
    'docs.step3.t': '활성화',
    'docs.step3.d': 'After Effects 를 열고 <b>Window ▸ Extensions ▸ You Name It - Support</b> 에서 키를 붙여넣어 활성화합니다. 나머지 패널 {others}개의 잠금이 바로 풀립니다.',
    'docs.install.menu': '패널마다 그 메뉴에 항목이 하나씩 있습니다:',
    'docs.upd.h': '업데이트',
    'docs.upd.d': '새 버전이 나오면 Support 패널에 알림이 뜹니다. 지금 업데이트를 누른 뒤 After Effects 를 다시 켜면 적용됩니다 — 실행 중인 패널은 자기 자신을 바꾸지 못합니다. 패널 안 설치가 안 되면 <a href="{notes}">업데이트 노트 페이지</a>에서 직접 내려받을 수 있습니다.',
    'docs.hand.h': '수동 설치',
    'docs.hand.d': 'After Effects 를 닫은 채로 .zxp 의 확장자를 .zip 으로 바꿔 압축을 풀고, 폴더 이름을 정확히 <code>com.donys.plugin.cep</code> 로 해서 아래 위치에 둡니다. 다른 이름, 특히 아포스트로피가 들어간 이름이면 패널이 끝없이 로딩만 합니다. 파일은 하나도 빼거나 더하지 않습니다 — 압축 안의 파일이 서명과 정확히 맞아야 하고, 어긋나면 패널이 빈 창으로 열립니다. 이전 판 위에 덮어서 풀었다면 폴더를 통째로 지우고 다시 풉니다.',
    'docs.rm.h': '제거',
    'docs.rm.d': '먼저 Support 패널에서 이 컴퓨터의 활성화를 해제합니다 — 안 하면 자리 하나가 계속 잡혀 있습니다. 그다음 ZXP Installer 에서 제거하거나 <code>com.donys.plugin.cep</code> 폴더를 지웁니다. 그 컴퓨터를 이미 쓸 수 없다면 <a href="{portal}" target="_blank" rel="noopener">고객 포털</a>에서 해제합니다.',
    'docs.fix.h': '안 될 때',
    'docs.fix.list': [
      '패널이 빈 창으로 열립니다 — 폴더 안 파일이 서명과 맞지 않습니다(대개 이전 판의 잔여 파일). 폴더를 통째로 지우고 다시 설치하세요.',
      '로딩만 계속됩니다 — 폴더 이름이 <code>com.donys.plugin.cep</code> 가 아닙니다. 이름을 바꾸세요.',
      'Window ▸ Extensions 에 아무것도 없습니다 — After Effects 가 2022 보다 오래됐거나 폴더 위치가 틀렸습니다. 위 경로를 확인하세요.',
      '업데이트가 쓰기 권한이 없다고 합니다 — 모든 사용자용 위치에 설치돼 있습니다. 관리자 권한으로 .zxp 를 다시 설치하거나, 사용자 폴더에 수동으로 설치하세요.',
    ],
    'docs.fix.mail': '그래도 안 되면 이 파일을 첨부해 <a href="mailto:support@younameit.works">support@younameit.works</a> 로 보내세요 — Windows <code>%TEMP%\\donys-update.log</code> · macOS <code>$TMPDIR/donys-update.log</code>.',

    'docs.spec.h': '사양',
    'docs.spec.price.k': '가격',
    'docs.spec.price.v': '{price} USD',
    'docs.spec.price.n': '일회 구매 · 세금은 나라마다 달라 결제 화면에 표시 · Polar',
    'docs.spec.host.k': '호스트 앱',
    'docs.spec.host.v': 'After Effects 2022 이상',
    'docs.spec.host.n': 'Window ▸ Extensions 에 "You Name It - …" 항목 {panels}개',
    'docs.spec.form.k': '설치 형태',
    'docs.spec.form.v': 'ZXP 확장',
    'docs.spec.form.n': '무료 ZXP Installer 또는 수동 설치 — <a href="#install">설치 안내</a>',
    'docs.spec.os.k': '운영체제',
    'docs.spec.os.v': 'Windows · macOS',
    'docs.spec.os.n': 'Depth Pass 는 Apple Silicon Mac 과 Windows 에서 돕니다 — 인텔 Mac 은 안 됩니다',
    'docs.spec.license.k': '라이선스',
    'docs.spec.license.v': '컴퓨터 2대 · 1인',
    'docs.spec.license.n': '활성화 해제는 Support 패널이나 <a href="{portal}" target="_blank" rel="noopener">고객 포털</a>에서 직접',
    'docs.spec.lang.k': '언어',
    'docs.spec.lang.v': '한국어 · English',
    'docs.spec.lang.n': '패널 안에서 전환',
    'docs.spec.net.k': '네트워크',
    'docs.spec.net.v': '7일마다 확인',
    'docs.spec.net.n': '오프라인 30일까지 · Chat 은 연결 필요',
    'docs.spec.support.k': '지원',
    'docs.spec.support.v': '<a href="mailto:support@younameit.works">support@younameit.works</a>',
    'docs.spec.support.n': '설치·라이선스·환불 문의 · 영업일 기준 48시간 안에 답하려고 합니다',

    'docs.cta.txt': '환불, Chat 구독, 컴퓨터 2대 — 사기 전에 묻는 것들은 제품 페이지에 답이 있습니다.',
    'docs.cta.faq': '자주 묻는 것 →',
  },
};

export default DOCS;
