/* 셸 사전 — 세 페이지(`/` · `/ae` · `/ae/docs`)가 같이 쓴다. 페이지 고유 문장은 여기 넣지 마라.
   🔴 법·연락처 줄은 **배관이 걸린 자리**다(proto4 정적 HTML 은 이 넷을 href 없는 텍스트로 잃어버렸다).
   지우면 결제 페이지가 약관 없이 나간다. */
import type { Dict } from './types';

const SHARED: Dict = {
  en: {
    's.plate': 'Plate',
    's.plate.cover': 'Cover',
    's.buy': 'Buy',
    's.buy.price': 'Buy — {price}',
    's.brand': 'You Name It',
    's.product': 'You Name It AE Plugin',
    's.toBrand': 'What we are',
    's.toProduct': 'AE Plugin',
    's.docs': 'Docs',
    's.ft.made': 'What we made',
    's.ft.support': 'Support',
    's.ft.brand': 'Brand',
    's.ft.legal': 'Legal',
    's.ft.docs': 'Docs — all {scripts} tools',
    's.ft.faq': 'Common questions',
    's.ft.specs': 'Install · specs',
    's.ft.notes': 'Release notes',
    's.ft.news': 'Newsletter',
    's.ft.contact': 'support@younameit.works',
    's.ft.terms': 'Terms',
    's.ft.privacy': 'Privacy Policy',
    's.ft.refund': 'Refunds',
    /* 사업자 줄(푸터 맨 밑) — 값은 `lib/product.ts` BUSINESS 가 채운다. 라벨만 여기. 전자상거래법 §10·§13 표시 의무. */
    's.biz.name': 'Company',
    's.biz.ceo': 'CEO',
    's.biz.regNo': 'Business Reg. No.',
    's.biz.verify': 'Verify',
    's.biz.mailOrder': 'Mail-order Sales Reg. No.',
    's.biz.address': 'Address',
    's.biz.phone': 'Tel',
    's.biz.email': 'Email',
    's.biz.hosting': 'Hosting',
    's.copyright': '© 2026 You Name It',
    /* 🔴 "세금 별도" 라고 단정하지 마라 — Polar 가 나라마다 다르게 붙인다(한국은 포함 표시, 미국·캐나다·인도는 별도). */
    's.legal.line': 'Sold by Polar as merchant of record. Tax is calculated at checkout.',
  },
  ko: {
    's.plate': '판',
    's.plate.cover': '표지',
    's.buy': '구매',
    's.buy.price': '구매 — {price}',
    's.brand': 'You Name It',
    's.product': 'You Name It AE Plugin',
    's.toBrand': '우리는 무엇인가',
    's.toProduct': 'AE Plugin',
    's.docs': 'Docs',
    's.ft.made': '만든 것',
    's.ft.support': '지원',
    's.ft.brand': '브랜드',
    's.ft.legal': '법',
    's.ft.docs': 'Docs — 툴 {scripts}종 전부',
    's.ft.faq': '자주 묻는 것',
    's.ft.specs': '설치 · 사양',
    's.ft.notes': '업데이트 노트',
    's.ft.news': '소식 받기',
    's.ft.contact': 'support@younameit.works',
    's.ft.terms': '이용약관',
    's.ft.privacy': '개인정보처리방침',
    's.ft.refund': '환불',
    's.biz.name': '상호',
    's.biz.ceo': '대표',
    's.biz.regNo': '사업자등록번호',
    's.biz.verify': '사업자정보 확인',
    's.biz.mailOrder': '통신판매업 신고번호',
    's.biz.address': '주소',
    's.biz.phone': '전화',
    's.biz.email': '이메일',
    's.biz.hosting': '호스팅 제공',
    's.copyright': '© 2026 You Name It',
    's.legal.line': '판매는 Polar 가 대행합니다(merchant of record). 세금은 결제 화면에서 계산됩니다.',
  },
};

export default SHARED;
